# Generated by Django 5.1.6 on 2025-02-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comtextbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=30)),
                ('title3', models.CharField(max_length=40)),
                ('text1', models.TextField()),
                ('quiz1', models.TextField()),
            ],
        ),
    ]
